version: "3.8"

services:
  super-linter:
    image: ghcr.io/super-linter/super-linter:slim-v7
    container_name: super-linter
    environment:
      - RUN_LOCAL=true
      - LOG_LEVEL=DEBUG
      - FILTER_REGEX_EXCLUDE=node_modules
    volumes:
      - .:/tmp/lint
    working_dir: /tmp/lint
