---
root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
plugins:
  - "@typescript-eslint"
  - "prettier"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
env:
  node: true
